In [501]:
import pandas as pd
import spacy
import re
from functools import reduce

In [470]:
nlp = spacy.load('en_core_web_lg')

In [510]:
def data_cleaning(file,state_name,state_id):
    df = pd.read_csv(file, engine='python',encoding='utf-8')
    stop_words = nlp.Defaults.stop_words
    content = [sent for sent in df['Requirements']]
    requirements = [req.split() for req in df['Requirements']]
    requirements = [req for reqs in requirements for req in reqs]
    requirements_cleaned = [word for word in requirements if word not in stop_words]
    
    
    '''Extracting the languages'''
    
    eng = re.compile("(English|english)")
    eng_matches = list(filter(eng.match, requirements_cleaned))
    eng_matches =['English' for word in eng_matches]

    ger = re.compile("(German|german)")
    ger_matches = list(filter(ger.match, requirements_cleaned))
    ger_matches =['German' for word in ger_matches]

    fre = re.compile("(French|french)")
    fre_matches = list(filter(fre.match, requirements_cleaned))
    fre_matches =['French' for word in fre_matches]

    russ = re.compile("(Russian|russian)")
    russ_matches = list(filter(russ.match, requirements_cleaned))
    russ_matches =['Russian' for word in russ_matches]

    tur = re.compile("(Turkish|turkish)")
    tur_matches = list(filter(tur.match, requirements_cleaned))
    tur_matches =['Turkish' for word in tur_matches]

    dan = re.compile("(Danish|danish)")
    dan_matches = list(filter(dan.match, requirements_cleaned))
    dan_matches =['Danish' for word in dan_matches]

    languages = [eng_matches, ger_matches, fre_matches, russ_matches, tur_matches, dan_matches]
    languages =[lang for langs in languages for lang in langs if lang]
    
    if len(languages) == 0:
        languages.append('NaN')
    
    language_df = pd.DataFrame(languages, columns=['Languages'])
    
    '''Extracting the programming languages'''

    python = re.compile("(Python|python)")
    python_matches = list(filter(python.match, requirements_cleaned))
    python_matches =['Python' for word in python_matches]

    sql = re.compile("(SQL|sql)")
    sql_matches = list(filter(sql.match, requirements_cleaned))
    sql_matches =['SQL' for word in sql_matches]

    java = re.compile("(Java)")
    java_matches = list(filter(java.findall, requirements_cleaned))
    java_matches =[word for word in java_matches if word == 'Java']

    js = re.compile("(JavaScript|Javascript)")
    js_matches = list(filter(js.match, requirements_cleaned))
    js_matches =['JavaScript' for word in js_matches]

    julia = re.compile("(Julia|julia)")
    julia_matches = list(filter(julia.match, requirements_cleaned))
    julia_matches =['Julia' for word in julia_matches]

    scala = re.compile("(Scala|scala)")
    scala_matches = list(filter(scala.match, requirements_cleaned))
    scala_matches =['Scala' for word in scala_matches]

    no_sql = re.compile("(nosql|NoSql|NoSQL)")
    no_sql_matches = list(filter(no_sql.match, requirements_cleaned))
    no_sql_matches =['NoSQL' for word in no_sql_matches]

    swift = re.compile("(swift|Swift)")
    swift_matches = list(filter(swift.match, requirements_cleaned))
    swift_matches =['Swift' for word in swift_matches]

    matlab = re.compile("(matlab|Matlab|MATLAB)")
    matlab_matches = list(filter(matlab.match, requirements_cleaned))
    matlab_matches =['Matlab' for word in matlab_matches]

    sas = re.compile("(SAS)")
    sas_matches = list(filter(sas.match, requirements_cleaned))
    sas_matches =['SAS' for word in sas_matches]

    perl = re.compile("(perl|Perl)")
    perl_matches = list(filter(perl.match, requirements_cleaned))
    perl_matches =['Perl' for word in perl_matches]

    php = re.compile("(php|PHP|Php)")
    php_matches = list(filter(php.match, requirements_cleaned))
    php_matches =['PHP' for word in php_matches]

    vba = re.compile("(VBA|vba)")
    vba_matches = list(filter(vba.match, requirements_cleaned))
    vba_matches =['VBA' for word in vba_matches]

    r_matches = [word for word in requirements_cleaned if word == 'R']

    programming = [python_matches,sql_matches,java_matches,js_matches,julia_matches,scala_matches,no_sql_matches,swift_matches,matlab_matches,sas_matches,perl_matches,php_matches,vba_matches, r_matches]
    programming = [program for programs in programming for program in programs if program]
    
    if len(programming) == 0:
        programming.append('NaN')
    
    programming_df = pd.DataFrame(programming, columns=['Programming Languages'])
    
    
    '''Extracting education: '''
    master = re.compile("(Master)")
    master_matches = list(filter(master.match, requirements_cleaned))
    master_matches =['Master' for word in master_matches]

    bachelor = re.compile("(Bachelor|bachelor)")
    bachelor_matches = list(filter(bachelor.match, requirements_cleaned))
    bachelor_matches =['Bachelor' for word in bachelor_matches]

    phd = re.compile("(PhD)")
    phd_matches = list(filter(phd.match, requirements_cleaned))
    phd_matches =['PHD' for word in phd_matches]

    education = [master_matches,phd_matches,bachelor_matches]
    education = [educ for educs in education for educ in educs if educ]
    
    if len(education) == 0:
        education.append('NaN')
    
    education_df = pd.DataFrame(education, columns=['Education'])
    
    '''Extracting visualization tools: '''
    
    tableau = re.compile("(Tableau|tableau)")
    tableau_matches = list(filter(tableau.match, requirements_cleaned))
    tableau_matches =['Tableau' for word in tableau_matches]


    qlik = re.compile("(QLIK|Qlik)")
    qlik_matches = list(filter(qlik.match, requirements_cleaned))
    qlik_matches =['QLIK' for word in qlik_matches]


    plotly = re.compile("(plotly|Plotly)")
    plotly_matches = list(filter(plotly.match, requirements_cleaned))
    plotly_matches =['Plotly' for word in plotly_matches]

    looker = re.compile("(looker|Looker)")
    looker_matches = list(filter(looker.match, requirements_cleaned))
    looker_matches =['Looker' for word in looker_matches]

    matplot = re.compile("(matplotlib|Matplotlib|matplot)")
    matplot_matches = list(filter(matplot.match, requirements_cleaned))
    matplot_matches =['Matplot' for word in matplot_matches]




    power_bi_matches = []
    search = []
    for word in content:
        if 'Power BI' in word or 'powerbi' in word:
            search.append(word)

    search =[str(sent) for sent in search]


    re_pattern = r"(Power BI| power bi)"

    for i in range(0, len(search)):
        match = re.findall(re_pattern, search[i])
        power_bi_matches.append(match)

    power_bi_matches = [match for matches in power_bi_matches for match in matches]


    visualizations = [tableau_matches,qlik_matches, plotly_matches, looker_matches, matplot_matches, power_bi_matches]
    visualizations =[viz for vizs in visualizations for viz in vizs if viz]
    
    if len(visualizations) == 0:
        visualizations.append('NaN')
    
    visualization_df = pd.DataFrame(visualizations, columns=['Visualizations'])
    
    '''Extracting packages and libraries: '''
    
    tensor = re.compile("(Tensor|tensor)")
    tensor_matches = list(filter(tensor.match, requirements_cleaned))
    tensor_matches =['Tensorflow' for word in tensor_matches]

    numpy = re.compile("(Numpy|numpy|NumPy)")
    numpy_matches = list(filter(numpy.match, requirements_cleaned))
    numpy_matches =['NumPy' for word in numpy_matches]

    scipy = re.compile("(scipy|Scipy)")
    scipy_matches = list(filter(scipy.match, requirements_cleaned))
    scipy_matches =['SciPy' for word in scipy_matches]

    pandas = re.compile("(pandas|Pandas|panda)")
    pandas_matches = list(filter(pandas.match, requirements_cleaned))
    pandas_matches =['Pandas' for word in pandas_matches]

    keras = re.compile("(Kera|Keras|keras|Kera)")
    keras_matches = list(filter(keras.match, requirements_cleaned))
    keras_matches =['Keras' for word in keras_matches]

    scikit = re.compile("(Scikitlearn|scikitLearn|scikitlearn|ScikitLearn)")
    scikit_matches = list(filter(scikit.match, requirements_cleaned))
    scikit_matches =['Scikitlearn' for word in scikit_matches]

    pytorch = re.compile("(pytorch|PyTorch|pyTorch)")
    pytorch_matches = list(filter(pytorch.match, requirements_cleaned))
    pytorch_matches =['PyTorch' for word in pytorch_matches]

    scrapy = re.compile("(scrapy|Scrapy)")
    scrapy_matches = list(filter(scrapy.match, requirements_cleaned))
    scrapy_matches =['Scrapy' for word in scrapy_matches]

    selenium = re.compile("(selenium|Selenium)")
    selenium_matches = list(filter(selenium.match, requirements_cleaned))
    selenium_matches =['Selenium' for word in selenium_matches]

    beautiful = re.compile("(beautifulsoup|BeautifulSoup|beautifulSoup|Beautifulsoup)")
    beautiful_matches = list(filter(beautiful.match, requirements_cleaned))
    beautiful_matches =['BeautifulSoup' for word in beautiful_matches]

    packages = [tensor_matches,numpy_matches,scipy_matches,pandas_matches,keras_matches,scikit_matches,pytorch_matches,scrapy_matches,selenium_matches,beautiful_matches]

    packages =[pack for packs in packages for pack in packs if pack]
    
    
    if len(packages) == 0:
        packages.append('NaN')
    
    packages_df = pd.DataFrame(packages, columns=['Packages and Libraries'])
    
    '''Extracting Tools: '''
    
    
    excel = re.compile("(excel|Excel)")
    excel_matches = list(filter(excel.match, requirements_cleaned))
    excel_matches = ['Excel' for word in excel_matches if word.lower() != 'excellent']


    power_point_matches = []
    power_point_search = []
    for word in content:
        if 'power point' in word.lower() or 'powerpoint' in word.lower():
            power_point_search.append(word)

    power_point_search =[str(sent) for sent in power_point_search]


    re_pattern = r"(Power Point|power point|powerpoint|PowerPoint)"

    for i in range(0, len(power_point_search)):
        match = re.findall(re_pattern, power_point_search[i])
        power_point_matches.append(match)

    power_point_matches = [match for matches in power_point_matches for match in matches]
    power_point_matches =['PowerPoint' for word in power_point_matches]





    google_analytics_matches = []
    google_analytics_search = []
    for word in content:
        if 'google analytics' in word.lower() or 'googleanalytics' in word.lower():
            google_analytics_search.append(word)

    google_analytics_search =[str(sent) for sent in google_analytics_search]


    re_pattern = r"(googleanalytics|google analytics|GoogleAnalytics|Google Analytics)"

    for i in range(0, len(google_analytics_search)):
        match = re.findall(re_pattern, google_analytics_search[i])
        google_analytics_matches.append(match)

    google_analytics_matches = [match for matches in google_analytics_matches for match in matches]
    google_analytics_matches =['Google Analytics' for word in google_analytics_matches]




    google_data_studio_matches = []
    google_data_studio_search = []
    for word in content:
        if 'Google Data Studio' in word or 'googledatastudio' in word.lower():
            google_data_studio_search.append(word)

    google_data_studio_search =[str(sent) for sent in google_data_studio_search]


    re_pattern = r"(google data studio|Google Data Studio|Google Data Studio)"

    for i in range(0, len(google_data_studio_search)):
        match = re.findall(re_pattern, google_data_studio_search[i])
        google_data_studio_matches.append(match)

    google_data_studio_matches = [match for matches in google_data_studio_matches for match in matches]
    google_data_studio_matches =['Google Data Studio' for word in google_data_studio_matches]



    adobe_analytics_matches = []
    adobe_analytics_search = []
    for word in content:
        if 'adobe analytics' in word.lower() or 'adobeanalytics' in word.lower():
            adobe_analytics_search.append(word)

    adobe_analytics_search =[str(sent) for sent in adobe_analytics_search]


    re_pattern = r"(adobeanalytics|Adobe Analytics|AdobeAnalytics)"

    for i in range(0, len(adobe_analytics_search)):
        match = re.findall(re_pattern, adobe_analytics_search[i])
        adobe_analytics_matches.append(match)

    adobe_analytics_matches = [match for matches in adobe_analytics_matches for match in matches]
    adobe_analytics_matches =['Adobe Analytics' for word in adobe_analytics_matches]
    
    tools = [power_point_matches,google_analytics_matches,google_data_studio_matches,adobe_analytics_matches,excel_matches]
    tools =[t for tool in tools for t in tool]
    
    if len(tools) == 0:
        tools.append('NaN')
    
    tools_df = pd.DataFrame(tools, columns=['Tools'])
    
    
    all_info = [tools,packages,visualizations,education,programming,languages ]
    max_length = reduce(max, [len(item) for item in all_info])
    
    state = [state_name for i in range(0,max_length)]
    state_number = [state_id for j in range(0, max_length)]
    
    state_df = pd.DataFrame(state, columns=['States'])
    state_ID = pd.DataFrame(state_number, columns=['State ID']) 
    
    df_combined = [state_ID, state_df, programming_df, language_df, education_df, visualization_df, packages_df, tools_df]
    
    
    final_df = pd.concat(df_combined, axis=1)
    return final_df

In [556]:
df = data_cleaning(file="16.1 Thuringia_requirements.csv", state_name='Thuringia',state_id= '16')

In [557]:
df

,State ID,States,Programming Languages,Languages,Education,Visualizations,Packages and Libraries,Tools
0,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
1,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
2,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
3,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
4,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
5,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
6,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
7,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
8,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
9,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
10,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
11,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
12,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
13,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
14,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
15,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
16,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
17,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
18,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
19,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
20,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
21,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
22,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
23,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
24,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
25,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
26,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
27,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
28,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
29,16,Thuringia,Python,English,NaN,Power BI,NaN,NaN
...,...,...,...,...,...,...,...,...
47,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
48,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
49,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
50,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
51,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
52,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
53,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
54,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
55,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
56,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
57,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
58,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
59,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
60,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
61,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
62,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
63,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
64,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
65,16,Thuringia,SQL,German,NaN,NaN,NaN,NaN
66,16,Thuringia,R,German,NaN,NaN,NaN,NaN
67,16,Thuringia,R,German,NaN,NaN,NaN,NaN
68,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
69,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
70,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
71,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
72,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
73,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
74,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
75,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN
76,16,Thuringia,NaN,German,NaN,NaN,NaN,NaN

In [558]:
df.to_csv("16.Thuringia_final.csv")